"""Team Matrix design system build.

Source of truth: tokens/team-matrix.tokens.json (W3C Design Tokens Format 2025.10).

Writes:
  tokens/tokens.css          CSS custom properties
  tokens/tailwind.preset.js  Tailwind CSS preset
  index.html                 the gallery (src/gallery.html with the CSS inlined)

Run from the repo root:  python3 build.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
T = json.loads((ROOT / "tokens/team-matrix.tokens.json").read_text())


def get(path):
    node = T
    for part in path.split("."):
        node = node[part]
    return node


def resolve(v):
    if isinstance(v, str) and v.startswith("{") and v.endswith("}"):
        return resolve(get(v[1:-1])["$value"])
    return v


def css_color(v):
    v = resolve(v)
    if isinstance(v, dict) and "colorSpace" in v:
        if "alpha" in v and v["alpha"] < 1:
            r, g, b = (round(x * 255) for x in v["components"])
            return f"rgba({r}, {g}, {b}, {v['alpha']})"
        return v.get("hex") or "#%02X%02X%02X" % tuple(round(x * 255) for x in v["components"])
    return str(v)


def css_dim(v):
    v = resolve(v)
    return f"{v['value']}{v['unit']}" if isinstance(v, dict) else str(v)


def css_family(v):
    v = resolve(v)
    return ", ".join(f'"{f}"' if " " in f else f for f in v)


def walk(node, prefix=""):
    for k, v in node.items():
        if k.startswith("$"):
            continue
        if isinstance(v, dict) and "$value" in v:
            yield prefix + k, v
        elif isinstance(v, dict):
            yield from walk(v, prefix + k + "-")


lines = [
    "/*",
    " * Team Matrix design system: tokens.css",
    " * Generated by build.py from tokens/team-matrix.tokens.json. Do not edit by hand.",
    " * Dark theme only. FIRST Tech Challenge Team #20870.",
    " */",
    '@import url("https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Poppins:wght@400;500;600;700&display=swap");',
    "",
    ":root {",
    "  color-scheme: dark;",
]
for name, tok in walk(T["primitive"]["color"], "tm-"):
    lines.append(f"  --{name}: {css_color(tok['$value'])};")
lines.append("")
for name, tok in walk(T["color"], "tm-"):
    lines.append(f"  --{name}: {css_color(tok['$value'])};")
lines.append("")
lines.append(f"  --tm-gradient-brand: {T['gradient']['brand']['$extensions']['org.team-matrix.css']};")
lines.append("")
lines.append(f"  --tm-font-heading: {css_family(T['font']['family']['heading']['$value'])};")
lines.append(f"  --tm-font-body: {css_family(T['font']['family']['body']['$value'])};")
for name, tok in walk(T["font"]["weight"], "tm-weight-"):
    lines.append(f"  --{name}: {resolve(tok['$value'])};")
for name, tok in walk(T["font"]["size"], "tm-size-"):
    lines.append(f"  --{name}: {css_dim(tok['$value'])};")
lines.append("")
for name, tok in walk(T["space"], "tm-space-"):
    lines.append(f"  --{name}: {css_dim(tok['$value'])};")
for name, tok in walk(T["radius"], "tm-radius-"):
    lines.append(f"  --{name}: {css_dim(tok['$value'])};")
for name, tok in walk(T["shadow"], "tm-shadow-"):
    s = tok["$value"]
    lines.append(f"  --{name}: {css_dim(s['offsetX'])} {css_dim(s['offsetY'])} {css_dim(s['blur'])} {css_dim(s['spread'])} {css_color(s['color'])};")
for name, tok in walk(T["duration"], "tm-duration-"):
    lines.append(f"  --{name}: {css_dim(tok['$value'])};")
for name, tok in walk(T["easing"], "tm-ease-"):
    lines.append(f"  --{name}: cubic-bezier({', '.join(str(x) for x in tok['$value'])});")
lines.append("}")
(ROOT / "tokens/tokens.css").write_text("\n".join(lines) + "\n")

# Tailwind preset
tw_colors = {
    "bg": {k: css_color(v["$value"]) for k, v in T["color"]["bg"].items() if not k.startswith("$")},
    "text": {k: css_color(v["$value"]) for k, v in T["color"]["text"].items() if not k.startswith("$")},
    "accent": {("DEFAULT" if k == "default" else k): css_color(v["$value"]) for k, v in T["color"]["accent"].items() if not k.startswith("$")},
    "status": {k: css_color(v["$value"]) for k, v in T["color"]["status"].items() if not k.startswith("$")},
    "alliance": {k: css_color(v["$value"]) for k, v in T["color"]["alliance"].items() if not k.startswith("$")},
}
preset = {
    "theme": {
        "extend": {
            "colors": {"tm": tw_colors},
            "fontFamily": {
                "heading": resolve(T["font"]["family"]["heading"]["$value"]),
                "body": resolve(T["font"]["family"]["body"]["$value"]),
            },
            "backgroundImage": {"tm-brand": T["gradient"]["brand"]["$extensions"]["org.team-matrix.css"]},
            "borderRadius": {f"tm-{k}": css_dim(v["$value"]) for k, v in T["radius"].items() if not k.startswith("$")},
        }
    }
}
(ROOT / "tokens/tailwind.preset.js").write_text(
    "// Team Matrix Tailwind preset. Generated by build.py. Usage: presets: [require('./tokens/tailwind.preset.js')]\n"
    "module.exports = " + json.dumps(preset, indent=2) + ";\n"
)

# Gallery
tokens_css = re.sub(r"^@import .*$\n?", "", (ROOT / "tokens/tokens.css").read_text(), flags=re.M)
comp_css = (ROOT / "css/team-matrix.css").read_text()
body = (ROOT / "src/gallery.html").read_text().replace("/*__TOKENS__*/", tokens_css).replace("/*__COMPONENTS__*/", comp_css)
cut = body.index("</style>") + len("</style>")
doc = ("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
       "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\n"
       + body[:cut] + "\n</head>\n<body>\n" + body[cut:] + "\n</body>\n</html>\n")
(ROOT / "index.html").write_text(doc)
print("built tokens.css, tailwind.preset.js, index.html")
