// Team Matrix Tailwind preset. Generated by build.py. Usage: presets: [require('./tokens/tailwind.preset.js')]
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "tm": {
          "bg": {
            "main": "#0E0C14",
            "second": "#513899",
            "subtle": "#1A142C",
            "logo": "#1A0A41"
          },
          "text": {
            "heading": "#FFFFFF",
            "body": "#D9D5E2",
            "muted": "#A6A3AE",
            "on-accent": "#0E0C14"
          },
          "accent": {
            "DEFAULT": "#A58BFF",
            "on-second": "#D2C4FF"
          },
          "status": {
            "warning": "#FFB547",
            "danger": "#FF7A93"
          },
          "alliance": {
            "red": "#FF5A6E",
            "blue": "#4D8DFF"
          }
        }
      },
      "fontFamily": {
        "heading": [
          "Bebas Neue",
          "Impact",
          "Arial Narrow",
          "sans-serif"
        ],
        "body": [
          "Poppins",
          "Segoe UI",
          "Arial",
          "sans-serif"
        ]
      },
      "backgroundImage": {
        "tm-brand": "radial-gradient(80% 90% at 17% 27%, #9E7CFF 0%, #3B2585 45%, #1A0A41 100%)"
      },
      "borderRadius": {
        "tm-sm": "6px",
        "tm-md": "12px",
        "tm-lg": "20px",
        "tm-pill": "999px"
      }
    }
  }
};
